#!/bin/bash

# Comment commit hook to ensure you specify the JIRA Ticket number
# HOW TO GET IT TO WORK
# Open a terminal and navigate to your project ROOT directory
<<INSTALLATION
wget https://raw.githubusercontent.com/drpain/bash/master/git/hooks/commit-msg
mv commit-msg .git/hooks/
chmod +x .git/hooks/commit-msg
INSTALLATION

# Search through the comment to ensure that it contains the correct format
operations_ticket="$(grep '^OP-[09]\{3,20\}' "$1")"
sprint_ticket="$(grep '^SPR-[09]\{3,20\}' "$1")"

# Ensure that either type of ticket's reference is added
if [ "$operations_ticket" == "" ] && [ "$sprint_ticket" == "" ]; then
	echo ""
	echo ""
    echo "ERROR: Jira reference not found"
    echo ""
    echo "SPRINT TICKETS"
    echo ""
    echo "The following format is required:"
    echo "SPR-<ticket number> ie: SPR-802 Comment..."
    echo ""
    echo ""
    echo "OPS TICKETS"
    echo ""
    echo "The following format is required:" 
    echo "OP-<ticket number> ie: OP-802 Comment..."
    echo ""
	echo ""
    exit 1
fi